### ISSUE TITLE
write unix /run/docker.sock->@: write: broken pipe

### ISSUE THREAD

**Issue by enfff** [tonynajjar/ros2_devcontainer_template#4]
First and foremost, thank you for making this template, it's amazing.

I was following the official beginner guide, to check if everything was working correctly. And indeed, these work fine:
```
ros2 run turtlesim turtlesim_node
ros2 run turtlesim turtle_teleop_key
```
However, at the end, when I ran commands like `ros2 node list`, `ros2 topic list`, `ros2 service list`, or `ros2 action list`, nothing was returned. Additionally, if I open `127.0.0.1:11511` in my browser (the automatically forwarded address), it loads indefinitely.

Running standard Ubuntu commands, such as `lsb_release -a` or `touch file.txt`, works fine too.

These are the most scaring lines `systemctl status docker` returns:

``` bash
lug 23 13:41:47 beddu dockerd[1149]: time="2024-07-23T13:41:47.202313251+02:00" level=error msg="Error running exec f7b00085e1b4b5f460af9a367145ffd28073a2b531677e0382f3cf6ddfde790e in container: exec attach faile
d: error attaching stdout stream: write unix /run/docker.sock->@: write: broken pipe"
lug 23 13:41:47 beddu dockerd[1149]: time="2024-07-23T13:41:47.211950809+02:00" level=info msg="ignoring event" container=225a5b9e448af38ea7b86d4d6037f3dd102a3ddd0305067728d017e39d9ccbd6 module=libcontainerd name
space=moby topic=/tasks/delete type="*events.TaskDelete"
```

I'm not sure if it's a problem with the template itself, or something wrong with my docker installation, but I'm posting it here anyways hoping to find more information that could help me solve this issue.

Extra information you might need
Arch Linux, kernel 6.9.10-arch1-1, GNOME 46.3.1, on a X11 session
Docker version 27.0.3, build 7d4bcd863a

**Comment by tonynajjar** [comment]
Hey @enfff, sorry for the late reply, I could not reproduce your issue with the default devcontainer in the repo. Can you share a minimum reproducible example that I could run?

Besides, if you're running `systemctl status docker` on your host (outside of the container) and are getting this issue then it highly suggests an issue with your docker setup independent from the devcontainer

**Comment by enfff** [comment]
Hello and thanks for your answer. 
I had the same identical issue with other devcontainers, which surely means there's something wrong with my own setup. 
Have a nice day!
